---
driver:
  name: vagrant

platforms:
- name: ubuntu-12.04
- name: ubuntu-10.04
- name: centos-6.4
- name: centos-5.9

suites:
- name: default
  run_list: ["recipe[bind]"]
  attributes:
    bind:
      zones:
        attribute: [ "example.com" ]
      options: [ "dnssec-validation no;", "check-names slave ignore;", "multi-master yes;", "provide-ixfr yes;", "request-ixfr yes;" ]
